### ISSUE TITLE
ActsAsTenant::Errors::NoTenantSet when model has global records

### ISSUE THREAD

**Issue by artplan1** [ErwinM/acts_as_tenant#241]
Hi!
We have `config.require_tenant = true` and models with `acts_as_tenant(:tenant, has_global_records: true)`. When we're trying to build/create such records in tenantless scope (tenant = nil) we're receiving `ActsAsTenant::Errors::NoTenantSet`. This is expected and unexpected in the same time :)
`ActsAsTenant.without_tenant` helps, but I'm wondering if this error should really be raised for models with global records?
Thanks.

**Comment by excid3** [comment]
That makes sense to me and does sound like a bug. 

Anyone using `has_global_records` that expects this to work differently?

**Comment by artplan1** [comment]
In my understanding `has_global_records ` doesn't mean ALL records are global for model, so it makes sense that in strict mode with `require_tenant = true` it raises exception (I assume it's happening in default scope)

But it doesn't make sense when we're trying to create global records

**Comment by artplan1** [comment]
test to reproduce this:
https://github.com/artplan1/acts_as_tenant/commit/5b246403e6d11e045c79fab83b7cc07c4e231295

summary:
```ruby
allow(ActsAsTenant.configuration).to receive_messages(require_tenant: true)
...
ActsAsTenant.current_tenant = nil
...
expect(GlobalProject.new(name: "foo new").valid?).to be(true)
```

error:
```
1) ActsAsTenant tenant required does not raise an error for global records
     Failure/Error: raise ActsAsTenant::Errors::NoTenantSet
     
     ActsAsTenant::Errors::NoTenantSet:
       ActsAsTenant::Errors::NoTenantSet
     # ./lib/acts_as_tenant/model_extensions.rb:20:in `block in acts_as_tenant'
     # ./spec/models/model_extensions_spec.rb:341:in `block (3 levels) in <top (required)>'
```

failing code:

```
default_scope lambda {
          if ActsAsTenant.configuration.require_tenant && ActsAsTenant.current_tenant.nil? && !ActsAsTenant.unscoped?
            raise ActsAsTenant::Errors::NoTenantSet
          end
```

**Comment by excid3** [comment]
There are two ways to do this.

`without_tenant` is the intended way to create global records when `require_tenant` is on:

```ruby
ActsAsTenant.without_tenant { GlobalProject.create!(name: "foo") }
```

On master (next release), `require_tenant` lambdas can take the relation being queried (#362). So you can skip the requirement for models with global records:

```ruby
config.require_tenant = ->(relation) { !ActsAsTenant.models_with_global_records.include?(relation&.klass) }
```

This also stops raising when those models are read without a tenant, so `without_tenant` is the safer choice if you only need it when creating global records.
